/*********************************************************************
 *        _       _         _
 *  _ __ | |_  _ | |  __ _ | |__   ___
 * | '__|| __|(_)| | / _` || '_ \ / __|
 * | |   | |_  _ | || (_| || |_) |\__ \
 * |_|    \__|(_)|_| \__,_||_.__/ |___/
 *
 * www.rt-labs.com
 * Copyright 2020 rt-labs AB, Sweden.
 *
 * This software is dual-licensed under GPLv3 and a commercial
 * license. See the file LICENSE.md distributed with this software for
 * full license information.
 ********************************************************************/

/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef LLDPLOCPORTTABLE_H
#define LLDPLOCPORTTABLE_H

#include "pf_includes.h"

/* function declarations */
void init_lldpLocPortTable (pnet_t * pnet);
void initialize_table_lldpLocPortTable (pnet_t * pnet);
Netsnmp_Node_Handler lldpLocPortTable_handler;
Netsnmp_First_Data_Point lldpLocPortTable_get_first_data_point;
Netsnmp_Next_Data_Point lldpLocPortTable_get_next_data_point;

/* column number definitions for table lldpLocPortTable */
#define COLUMN_LLDPLOCPORTNUM       1
#define COLUMN_LLDPLOCPORTIDSUBTYPE 2
#define COLUMN_LLDPLOCPORTID        3
#define COLUMN_LLDPLOCPORTDESC      4
#endif /* LLDPLOCPORTTABLE_H */
