/*
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

p-net Profinet device stack
===========================

Copyright 2018 rt-labs AB

This instance of p-net is licensed for use in a specific product, as
follows:

Company: Bender GmbH & Co. KG
Product: COMTRAXX
Product description: COMTRAXX products provided by Bender GmbH & Co. KG

Use of this instance of p-net in other products is not allowed.

You are hereby given a non-exclusive, non-transferable license to use
the SOFTWARE and documentation according to the SOFTWARE LICENSE
AGREEMENT document shipped together with this instance of the
SOFTWARE. The SOFTWARE LICENSE AGREEMENT prohibits copying and
redistribution of the SOFTWARE.  It prohibits reverse-engineering
activities.  It limits warranty and liability on behalf of rt-labs.
The details of these terms are explained in subsequent chapters of the
SOFTWARE LICENSE AGREEMENT.
-----BEGIN PGP SIGNATURE-----

iQEzBAEBCgAdFiEE1e4U+gPgGJXLsxxLZlG0bopmiXIFAl/TMvQACgkQZlG0bopm
iXJE1QgAlEKblKkIrLF+hVRm6I1IfbGV6VWnBx+9IPwaHZmgQZAVTOlp4RHiNAre
Il1l1xheENWpuihbVlvz5hMCVto4fkT13IUXxOo9Va9MK8lm6JOu2lYpl1HgVIwV
R6I6dsWLeNBSBaA38DDBHIfjP4LBZC/HVYO2ISc3/OKutqasz/WIp+AjAURiKRsf
yaWGay88FITHymmqJpGaWzB+jAOvRFs8hW/GsOyX/r17AK5F5N51O+UqUTKAWNPT
f6M8QF0b07Hw+eOuB7A/0D5nvSl/rOd9LvYkiUhIUmQdHqERNkF9EJdroIjxTMXi
lmoOkPEqyGV58fh7JjMYlI60sPlGBw==
=TaN+
-----END PGP SIGNATURE-----
*/

/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef LLDPXDOT3LOCPORTTABLE_H
#define LLDPXDOT3LOCPORTTABLE_H

#include "pf_includes.h"

/* function declarations */
void init_lldpXdot3LocPortTable (pnet_t * pnet);
void initialize_table_lldpXdot3LocPortTable (pnet_t * pnet);
Netsnmp_Node_Handler lldpXdot3LocPortTable_handler;
Netsnmp_First_Data_Point lldpXdot3LocPortTable_get_first_data_point;
Netsnmp_Next_Data_Point lldpXdot3LocPortTable_get_next_data_point;

/* column number definitions for table lldpXdot3LocPortTable */
#define COLUMN_LLDPXDOT3LOCPORTAUTONEGSUPPORTED     1
#define COLUMN_LLDPXDOT3LOCPORTAUTONEGENABLED       2
#define COLUMN_LLDPXDOT3LOCPORTAUTONEGADVERTISEDCAP 3
#define COLUMN_LLDPXDOT3LOCPORTOPERMAUTYPE          4
#endif /* LLDPXDOT3LOCPORTTABLE_H */
