/*
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

p-net Profinet device stack
===========================

Copyright 2018 rt-labs AB

This instance of p-net is licensed for use in a specific product, as
follows:

Company: Bender GmbH & Co. KG
Product: COMTRAXX
Product description: COMTRAXX products provided by Bender GmbH & Co. KG

Use of this instance of p-net in other products is not allowed.

You are hereby given a non-exclusive, non-transferable license to use
the SOFTWARE and documentation according to the SOFTWARE LICENSE
AGREEMENT document shipped together with this instance of the
SOFTWARE. The SOFTWARE LICENSE AGREEMENT prohibits copying and
redistribution of the SOFTWARE.  It prohibits reverse-engineering
activities.  It limits warranty and liability on behalf of rt-labs.
The details of these terms are explained in subsequent chapters of the
SOFTWARE LICENSE AGREEMENT.
-----BEGIN PGP SIGNATURE-----

iQEzBAEBCgAdFiEE1e4U+gPgGJXLsxxLZlG0bopmiXIFAl/TMvQACgkQZlG0bopm
iXJE1QgAlEKblKkIrLF+hVRm6I1IfbGV6VWnBx+9IPwaHZmgQZAVTOlp4RHiNAre
Il1l1xheENWpuihbVlvz5hMCVto4fkT13IUXxOo9Va9MK8lm6JOu2lYpl1HgVIwV
R6I6dsWLeNBSBaA38DDBHIfjP4LBZC/HVYO2ISc3/OKutqasz/WIp+AjAURiKRsf
yaWGay88FITHymmqJpGaWzB+jAOvRFs8hW/GsOyX/r17AK5F5N51O+UqUTKAWNPT
f6M8QF0b07Hw+eOuB7A/0D5nvSl/rOd9LvYkiUhIUmQdHqERNkF9EJdroIjxTMXi
lmoOkPEqyGV58fh7JjMYlI60sPlGBw==
=TaN+
-----END PGP SIGNATURE-----
*/

/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef LLDPXPNOLOCTABLE_H
#define LLDPXPNOLOCTABLE_H

#include "pf_includes.h"

/* function declarations */
void init_lldpXPnoLocTable (pnet_t * pnet);
void initialize_table_lldpXPnoLocTable (pnet_t * pnet);
Netsnmp_Node_Handler lldpXPnoLocTable_handler;
Netsnmp_First_Data_Point lldpXPnoLocTable_get_first_data_point;
Netsnmp_Next_Data_Point lldpXPnoLocTable_get_next_data_point;

/* column number definitions for table lldpXPnoLocTable */
#define COLUMN_LLDPXPNOLOCLPDVALUE                                 1
#define COLUMN_LLDPXPNOLOCPORTTXDVALUE                             2
#define COLUMN_LLDPXPNOLOCPORTRXDVALUE                             3
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT2                            4
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT3                            5
#define COLUMN_LLDPXPNOLOCPORTNOS                                  6
#define COLUMN_LLDPXPNOLOCPORTMRPUUID                              7
#define COLUMN_LLDPXPNOLOCPORTMRRTSTATUS                           8
#define COLUMN_LLDPXPNOLOCPORTPTCPMASTER                           9
#define COLUMN_LLDPXPNOLOCPORTPTCPSUBDOMAINUUID                    10
#define COLUMN_LLDPXPNOLOCPORTPTCPIRDATAUUID                       11
#define COLUMN_LLDPXPNOLOCPORTMODERT3                              12
#define COLUMN_LLDPXPNOLOCPORTPERIODLENGTH                         13
#define COLUMN_LLDPXPNOLOCPORTPERIODVALIDITY                       14
#define COLUMN_LLDPXPNOLOCPORTREDOFFSET                            15
#define COLUMN_LLDPXPNOLOCPORTREDVALIDITY                          16
#define COLUMN_LLDPXPNOLOCPORTORANGEOFFSET                         17
#define COLUMN_LLDPXPNOLOCPORTORANGEVALIDITY                       18
#define COLUMN_LLDPXPNOLOCPORTGREENOFFSET                          19
#define COLUMN_LLDPXPNOLOCPORTGREENVALIDITY                        20
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT3OPTIMIZATIONSUPPORTED       21
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT3PREAMBLESHORTENINGSUPPORTED 22
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT3PREAMBLESHORTENING          23
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT3FRAGMENTATIONSUPPORTED      24
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT3FRAGMENTATION               25
#define COLUMN_LLDPXPNOLOCPORTOPERMAUTYPEEXTENSION                 26
#define COLUMN_LLDPXPNOLOCPORTMRPICROLE                            27
#define COLUMN_LLDPXPNOLOCPORTMRPICDOMAINID                        28
#endif /* LLDPXPNOLOCTABLE_H */
