/*********************************************************************
 *        _       _         _
 *  _ __ | |_  _ | |  __ _ | |__   ___
 * | '__|| __|(_)| | / _` || '_ \ / __|
 * | |   | |_  _ | || (_| || |_) |\__ \
 * |_|    \__|(_)|_| \__,_||_.__/ |___/
 *
 * www.rt-labs.com
 * Copyright 2020 rt-labs AB, Sweden.
 *
 * This software is dual-licensed under GPLv3 and a commercial
 * license. See the file LICENSE.md distributed with this software for
 * full license information.
 ********************************************************************/

/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef LLDPXPNOLOCTABLE_H
#define LLDPXPNOLOCTABLE_H

#include "pf_includes.h"

/* function declarations */
void init_lldpXPnoLocTable (pnet_t * pnet);
void initialize_table_lldpXPnoLocTable (pnet_t * pnet);
Netsnmp_Node_Handler lldpXPnoLocTable_handler;
Netsnmp_First_Data_Point lldpXPnoLocTable_get_first_data_point;
Netsnmp_Next_Data_Point lldpXPnoLocTable_get_next_data_point;

/* column number definitions for table lldpXPnoLocTable */
#define COLUMN_LLDPXPNOLOCLPDVALUE                                 1
#define COLUMN_LLDPXPNOLOCPORTTXDVALUE                             2
#define COLUMN_LLDPXPNOLOCPORTRXDVALUE                             3
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT2                            4
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT3                            5
#define COLUMN_LLDPXPNOLOCPORTNOS                                  6
#define COLUMN_LLDPXPNOLOCPORTMRPUUID                              7
#define COLUMN_LLDPXPNOLOCPORTMRRTSTATUS                           8
#define COLUMN_LLDPXPNOLOCPORTPTCPMASTER                           9
#define COLUMN_LLDPXPNOLOCPORTPTCPSUBDOMAINUUID                    10
#define COLUMN_LLDPXPNOLOCPORTPTCPIRDATAUUID                       11
#define COLUMN_LLDPXPNOLOCPORTMODERT3                              12
#define COLUMN_LLDPXPNOLOCPORTPERIODLENGTH                         13
#define COLUMN_LLDPXPNOLOCPORTPERIODVALIDITY                       14
#define COLUMN_LLDPXPNOLOCPORTREDOFFSET                            15
#define COLUMN_LLDPXPNOLOCPORTREDVALIDITY                          16
#define COLUMN_LLDPXPNOLOCPORTORANGEOFFSET                         17
#define COLUMN_LLDPXPNOLOCPORTORANGEVALIDITY                       18
#define COLUMN_LLDPXPNOLOCPORTGREENOFFSET                          19
#define COLUMN_LLDPXPNOLOCPORTGREENVALIDITY                        20
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT3OPTIMIZATIONSUPPORTED       21
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT3PREAMBLESHORTENINGSUPPORTED 22
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT3PREAMBLESHORTENING          23
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT3FRAGMENTATIONSUPPORTED      24
#define COLUMN_LLDPXPNOLOCPORTSTATUSRT3FRAGMENTATION               25
#define COLUMN_LLDPXPNOLOCPORTOPERMAUTYPEEXTENSION                 26
#define COLUMN_LLDPXPNOLOCPORTMRPICROLE                            27
#define COLUMN_LLDPXPNOLOCPORTMRPICDOMAINID                        28
#endif /* LLDPXPNOLOCTABLE_H */
