/*
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

p-net Profinet device stack
===========================

Copyright 2018 rt-labs AB

This instance of p-net is licensed for use in a specific product, as
follows:

Company: Bender GmbH & Co. KG
Product: COMTRAXX
Product description: COMTRAXX products provided by Bender GmbH & Co. KG

Use of this instance of p-net in other products is not allowed.

You are hereby given a non-exclusive, non-transferable license to use
the SOFTWARE and documentation according to the SOFTWARE LICENSE
AGREEMENT document shipped together with this instance of the
SOFTWARE. The SOFTWARE LICENSE AGREEMENT prohibits copying and
redistribution of the SOFTWARE.  It prohibits reverse-engineering
activities.  It limits warranty and liability on behalf of rt-labs.
The details of these terms are explained in subsequent chapters of the
SOFTWARE LICENSE AGREEMENT.
-----BEGIN PGP SIGNATURE-----

iQEzBAEBCgAdFiEE1e4U+gPgGJXLsxxLZlG0bopmiXIFAl/TMvQACgkQZlG0bopm
iXJE1QgAlEKblKkIrLF+hVRm6I1IfbGV6VWnBx+9IPwaHZmgQZAVTOlp4RHiNAre
Il1l1xheENWpuihbVlvz5hMCVto4fkT13IUXxOo9Va9MK8lm6JOu2lYpl1HgVIwV
R6I6dsWLeNBSBaA38DDBHIfjP4LBZC/HVYO2ISc3/OKutqasz/WIp+AjAURiKRsf
yaWGay88FITHymmqJpGaWzB+jAOvRFs8hW/GsOyX/r17AK5F5N51O+UqUTKAWNPT
f6M8QF0b07Hw+eOuB7A/0D5nvSl/rOd9LvYkiUhIUmQdHqERNkF9EJdroIjxTMXi
lmoOkPEqyGV58fh7JjMYlI60sPlGBw==
=TaN+
-----END PGP SIGNATURE-----
*/

/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#undef LOG_DEBUG
#undef LOG_WARNING
#undef LOG_INFO
#undef LOG_ERROR
#undef LOG_FATAL

#include "lldpLocalSystemData.h"

/** Initializes the lldpLocalSystemData module */
void init_lldpLocalSystemData (pnet_t * pnet)
{
   const oid lldpLocChassisIdSubtype_oid[] = {1, 0, 8802, 1, 1, 2, 1, 3, 1};
   const oid lldpLocChassisId_oid[] = {1, 0, 8802, 1, 1, 2, 1, 3, 2};
   netsnmp_handler_registration * reg;

   netsnmp_register_scalar (
      reg = netsnmp_create_handler_registration (
         "lldpLocChassisIdSubtype",
         handle_lldpLocChassisIdSubtype,
         lldpLocChassisIdSubtype_oid,
         OID_LENGTH (lldpLocChassisIdSubtype_oid),
         HANDLER_CAN_RONLY));

   reg->my_reg_void = pnet;

   netsnmp_register_scalar (
      reg = netsnmp_create_handler_registration (
         "lldpLocChassisId",
         handle_lldpLocChassisId,
         lldpLocChassisId_oid,
         OID_LENGTH (lldpLocChassisId_oid),
         HANDLER_CAN_RONLY));

   reg->my_reg_void = pnet;
}

int handle_lldpLocChassisIdSubtype (
   netsnmp_mib_handler * handler,
   netsnmp_handler_registration * reginfo,
   netsnmp_agent_request_info * reqinfo,
   netsnmp_request_info * requests)
{
   pnet_t * pnet = reginfo->my_reg_void;
   pf_lldp_chassis_id_t chassis_id;

   /* We are never called for a GETNEXT if it's registered as a
      "instance", as it's "magically" handled for us.  */

   /* a instance handler also only hands us one request at a time, so
      we don't need to loop over a list of requests; we'll only get one. */

   pf_snmp_get_chassis_id (pnet, &chassis_id);

   switch (reqinfo->mode)
   {

   case MODE_GET:
      snmp_set_var_typed_integer (
         requests->requestvb,
         ASN_INTEGER,
         chassis_id.subtype);
      break;

   default:
      /* we should never get here, so this is a really bad error */
      LOG_ERROR (
         PF_SNMP_LOG,
         "lldpLocalSystemData(%d): unknown mode (%d)\n",
         __LINE__,
         reqinfo->mode);
      return SNMP_ERR_GENERR;
   }

   return SNMP_ERR_NOERROR;
}

int handle_lldpLocChassisId (
   netsnmp_mib_handler * handler,
   netsnmp_handler_registration * reginfo,
   netsnmp_agent_request_info * reqinfo,
   netsnmp_request_info * requests)
{
   pnet_t * pnet = reginfo->my_reg_void;
   pf_lldp_chassis_id_t chassis_id;

   /* We are never called for a GETNEXT if it's registered as a
      "instance", as it's "magically" handled for us.  */

   /* a instance handler also only hands us one request at a time, so
      we don't need to loop over a list of requests; we'll only get one. */

   pf_snmp_get_chassis_id (pnet, &chassis_id);

   switch (reqinfo->mode)
   {

   case MODE_GET:
      snmp_set_var_typed_value (
         requests->requestvb,
         ASN_OCTET_STR,
         chassis_id.string,
         chassis_id.len);
      break;

   default:
      /* we should never get here, so this is a really bad error */
      LOG_ERROR (
         PF_SNMP_LOG,
         "lldpLocalSystemData(%d): unknown mode (%d)\n",
         __LINE__,
         reqinfo->mode);
      return SNMP_ERR_GENERR;
   }

   return SNMP_ERR_NOERROR;
}
