/*********************************************************************
 *        _       _         _
 *  _ __ | |_  _ | |  __ _ | |__   ___
 * | '__|| __|(_)| | / _` || '_ \ / __|
 * | |   | |_  _ | || (_| || |_) |\__ \
 * |_|    \__|(_)|_| \__,_||_.__/ |___/
 *
 * www.rt-labs.com
 * Copyright 2020 rt-labs AB, Sweden.
 *
 * This software is dual-licensed under GPLv3 and a commercial
 * license. See the file LICENSE.md distributed with this software for
 * full license information.
 ********************************************************************/

/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef LLDPLOCALSYSTEMDATA_H
#define LLDPLOCALSYSTEMDATA_H

#include "pf_includes.h"

/* function declarations */
void init_lldpLocalSystemData (pnet_t * pnet);
Netsnmp_Node_Handler handle_lldpLocChassisIdSubtype;
Netsnmp_Node_Handler handle_lldpLocChassisId;
Netsnmp_Node_Handler handle_lldpLocSysName;
Netsnmp_Node_Handler handle_lldpLocSysDesc;
Netsnmp_Node_Handler handle_lldpLocSysCapSupported;
Netsnmp_Node_Handler handle_lldpLocSysCapEnabled;

#endif /* LLDPLOCALSYSTEMDATA_H */
