/*********************************************************************
 *        _       _         _
 *  _ __ | |_  _ | |  __ _ | |__   ___
 * | '__|| __|(_)| | / _` || '_ \ / __|
 * | |   | |_  _ | || (_| || |_) |\__ \
 * |_|    \__|(_)|_| \__,_||_.__/ |___/
 *
 * www.rt-labs.com
 * Copyright 2020 rt-labs AB, Sweden.
 *
 * This software is dual-licensed under GPLv3 and a commercial
 * license. See the file LICENSE.md distributed with this software for
 * full license information.
 ********************************************************************/

/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.iterate.conf
 */
#ifndef LLDPREMTABLE_H
#define LLDPREMTABLE_H

#include "pf_includes.h"

/* function declarations */
void init_lldpRemTable (pnet_t * pnet);
void initialize_table_lldpRemTable (pnet_t * pnet);
Netsnmp_Node_Handler lldpRemTable_handler;
Netsnmp_First_Data_Point lldpRemTable_get_first_data_point;
Netsnmp_Next_Data_Point lldpRemTable_get_next_data_point;

/* column number definitions for table lldpRemTable */
#define COLUMN_LLDPREMTIMEMARK         1
#define COLUMN_LLDPREMLOCALPORTNUM     2
#define COLUMN_LLDPREMINDEX            3
#define COLUMN_LLDPREMCHASSISIDSUBTYPE 4
#define COLUMN_LLDPREMCHASSISID        5
#define COLUMN_LLDPREMPORTIDSUBTYPE    6
#define COLUMN_LLDPREMPORTID           7
#define COLUMN_LLDPREMPORTDESC         8
#define COLUMN_LLDPREMSYSNAME          9
#define COLUMN_LLDPREMSYSDESC          10
#define COLUMN_LLDPREMSYSCAPSUPPORTED  11
#define COLUMN_LLDPREMSYSCAPENABLED    12
#endif /* LLDPREMTABLE_H */
