/*********************************************************************
 *        _       _         _
 *  _ __ | |_  _ | |  __ _ | |__   ___
 * | '__|| __|(_)| | / _` || '_ \ / __|
 * | |   | |_  _ | || (_| || |_) |\__ \
 * |_|    \__|(_)|_| \__,_||_.__/ |___/
 *
 * www.rt-labs.com
 * Copyright 2020 rt-labs AB, Sweden.
 *
 * This software is dual-licensed under GPLv3 and a commercial
 * license. See the file LICENSE.md distributed with this software for
 * full license information.
 ********************************************************************/

/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef SYSTEM_MIB_H
#define SYSTEM_MIB_H

#include "pf_includes.h"

/* function declarations */
void init_system_mib (pnet_t * pnet);
Netsnmp_Node_Handler handle_sysDescr;
Netsnmp_Node_Handler handle_sysObjectID;
Netsnmp_Node_Handler handle_sysUpTime;
Netsnmp_Node_Handler handle_sysContact;
Netsnmp_Node_Handler handle_sysName;
Netsnmp_Node_Handler handle_sysLocation;
Netsnmp_Node_Handler handle_sysServices;

#endif /* SYSTEM_MIB_H */
